config/routes.rb
Lodgistics::Application.routes.draw do
  require 'sidekiq/web'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  authenticate :admin do
    mount Blazer::Engine, at: "admin/intelligence"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    # registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }, skip: [:registrations]

  %w( 403 404 500 ).each do |code|
    get code, to: "errors#show", code: code
  end

  namespace :corporate do
    root to: 'pages#dashboard'
    resources :settings, only: [:index]
    resources :property_connections, only: [:show, :update]
    resources :purchase_requests, only: [:edit, :update], path: 'requests'
    get '/spend_budget_by_hotel_data' => 'pages#spend_budget_by_hotel', as: 'spend_budget_by_hotel_data'
    get '/work_order_clouds' => 'pages#work_order_clouds', as: 'work_order_clouds'
    get '/open_work_order_by_hotel' => 'pages#open_work_orders_by_hotel', as: 'open_work_orders_by_hotel'
  end

  namespace :maintenance do
    root to: 'pages#dashboard' # probably need to move it under /dashboard, @HUGO
    get :setup, to: 'setup#index', as: :setup
    get '/setup/rooms', to: 'setup#rooms', as: :setup_rooms
    get '/setup/public_areas', to: 'setup#public_areas', as: :setup_public_areas
    get '/setup/equipment', to: 'setup#equipment', as: :setup_equipment
    resources :rooms, only: [:show, :index, :create, :update] do
      get :inspection, on: :collection
      get :inspect, on: :member
    end
    resources :checklist_items, only: [:index, :create, :update,:destroy]
    resources :cycles, only: [:create] do
      post :create_next, on: :collection
    end
    resources :checklist_item_maintenances, only: [:index, :create, :destroy] do
      member do
        post :inspect
        delete :cancel_inspect
      end

      collection do
        get :equipment
      end
    end
    resources :public_areas, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :checklist_items
        get :inspection
      end
      get :inspect, on: :member
    end
    resources :records, only: [:index, :update, :destroy] do
      member do
        post :complete_inspection
        post :cancel_inspection
      end
    end
    resources :work_orders
    resources :materials, only: [:index, :create, :update, :destroy]
    resources :equipment_types, only: [:index, :create, :update, :destroy] do
      resources :equipment_checklist_items, only: [:index, :create, :show, :update, :destroy]
    end
    resources :equipments, only: [:index, :show, :create, :update, :destroy]

    get '/week_vs_completed_rooms_data' => 'pages#week_vs_completed_rooms_data', as: 'week_vs_completed_rooms_data'
    get '/pm_room_progress_data' => 'pages#pm_room_progress_data', as: 'pm_room_progress_data'
  end

  namespace :admin do
    root to: 'pages#dashboard'
    resources :users, only: [:edit, :update]
    resources :customers, only: [:new, :create, :show]
  end

  devise_for :admins, path: 'admin', controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords'
                      }

  resource :corporate_connections

  get :spend_vs_budgets_data, to: 'pages#spend_vs_budgets_data'

  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  authenticated :admin do
    root 'pages#dashboard', as: :admin_authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
    namespace :users, as: :user do
      put "/confirm" => "confirmations#confirm", as: :confirm
      put '/switch_current_property', to: 'sessions#switch_current_property', as: :switch_current_property
      resource :registration, only: [:edit, :update]
    end
  end
  resources :property_settings, path: 'settings', only: [:index]
  resources :categories, :locations, :lists do
    get 'rearrange', on: :member
    get 'destroy', on: :collection, path: 'destroy', as: 'destroy'
  end
  resources :items do
    collection do
      get 'start_order'
      get 'edit_multiple_tags'
      put 'update_multiple_tags'
      get :new_import
      post :import
      get 'destroy', path: 'destroy', as: 'destroy'
    end
  end
  resources :permissions, only: [:index] do
    collection do
      post 'update_all'
    end
  end
  resources :properties, only: [:show, :index, :update]
  resources :tags do
    get 'rearrange', on: :member
  end
  resources :purchase_orders, except: [:edit, :new, :create], path: 'orders' do
    member do
      post :send_fax, to: 'fax#create'
      get :fax_status, to: 'fax#show'
      post :update_fax, to: 'fax#update'
      post :send_email, to: 'email#create'
      post :send_vpt, to: 'vpt#create'
      get :print
    end
  end
  resources :purchase_receipts, only: [:new, :create], path: 'receipts'
  resources :purchase_requests, path: 'requests' do
    member do
      get :inventory_print
    end
  end
  resources :users do
    member do
      get :change_password
    end

    collection do
      post :valid_username
      post :confirm_username
    end
  end
  resources :messages
  resources :budgets

  resources :reports do
    member do
      put :favorite
    end
    collection do
      get :favorites
      #get *Report.pluck(:permalink).map{|p| p + '_data'} if Report.any?
      get :trending_cloud
      scope :render do
        get :vendor_spend
        get :category_spend
        get :items_consumption
        get :item_orders_chart_data
        get :items_spend
        get :item_price_variance
        get :inventory_vs_ordering
        get :maintenance_work_orders
        get :pm_productivity_report
        get :maintenance_pm_productivity_data
        get :room_pm_progress_data
        get :work_order_productivity_data
        get :guest_room_pm_analysis
        get :public_area_pm_analysis
        get :equipment_pm_analysis
        get :work_order_trendings
      end
    end
  end


  resources :vendors
  resources :room_types
  resources :departments
  resources :notifications
  resources :activities, only: [:index]
  resources :join_invitations do
    get 'accept', on: :member
  end
  # resources :guest_logs do
  #   get 'like', on: :member
  #   post 'set_alarm', on: :collection
  #   get 'check_alarm', on: :member
  #   delete 'remove_alarm', on: :member
  # end

  namespace :engage do
    get :dashboard, to: 'dashboard#index', as: :dashboard
    resources :messages, only: [:index, :create, :update]
    resources :entities, only: [:index, :create, :update, :destroy]
  end

  post 'punchout/:property_id/:vendor_id/shopping_cart', to: "punchout#shopping_cart", as: 'punchout_shopping_cart'
  get 'punchout/:property_id/:vendor_id', to: "punchout#create", as: 'start_punchout'

  get 'analytics', to: "analytics#index"
  get 'forecasts/(week/:year/:month/:day)', to: "forecasts#index", as: "forecasts"
  put 'forecast', to: "forecasts#update", as: "update_forecast"

  get '/fax', to: 'fax#show'
  post '/fax', to: 'fax#create'
  post '/phaxio', to: 'fax#update'
  get 'dashboard', to: 'pages#dashboard', :as => :dashboard
  get 'pages/home'
  # authenticated :user do
  #   root to: 'pages#dashboard'
  # end

  #root to: 'users/sessions#new'
  if Rails.env.development? or Rails.env.qa?
    mount MailerPreview => 'mailer_view'
    mount Sidekiq::Web, at: '/sidekiq'
  end

end

app/controllers/maintenance/base_controller.rb
class Maintenance::BaseController < ApplicationController
  before_filter :authenticate_user!
  before_action :check_permissions
  before_action :check_current_cycles_are_finished

  add_breadcrumb I18n.t("controllers.maintenance.root"), :maintenance_root_path

  private

  def check_permissions
    authorize :access, :maintenance?
  end

  # returns an array of cycles that are finished by the moment of checking
  # example: [:room]
  def check_current_cycles_are_finished
    finished_cycles = Maintenance::Cycle::CYCLE_TYPES
    .map{ |c_type| current_cycle(c_type) }.compact
    .select{ |cycle| cycle.is_over? }
    # to test messages uncomment next line:
    # finished_cycles = [current_cycle(:room), current_cycle(:public_area)]
    messages = render_to_string(partial: 'maintenance/shared/cycle_expired_alert', locals: {finished_cycles: finished_cycles})
    flash[:sticky_messages] = [[:alert, messages]] if finished_cycles.any?
  end

  def send_notification_and_mail_to_assignee(work_order)
    if @work_order.assigned_to
      MaintenanceWorkOrderMailer.work_order_notification_to_assignee(work_order).deliver!
      Notification.assigned_work_order(work_order)
      WorkOrderWorker.perform_async(work_order.id)
    end
  end

  def authorize_maintenance
    authorize :access, :pm?
  end

  def authorize_inspection
    authorize :access, :inspection?
  end

  def authorize_work_order
    authorize :access, :work_order?
  end

  def authorize_pm_setup
    authorize :access, :pm_setup?
  end

end

app/controllers/maintenance/checklist_item_maintenances_controller.rb
class Maintenance::ChecklistItemMaintenancesController < Maintenance::BaseController

  before_filter :get_maintainable, only: [:index, :create, :inspect, :equipment]

  def index
    render json: @maintainable.maintenance_records.find(params[:record_id]).to_json(
         include: { checklist_item_maintenances: { include: [:work_order, :inspection_work_order] } }
      ), status: 200
  end

  def equipment
    render json: @maintainable.maintenance_records.where(id: params[:record_id]).first.to_json(
               include: { checklist_item_maintenances: { include: [:work_order, :inspection_work_order] } }
           ), status: 200
  end

  def create
    if !policy(Maintenance::ChecklistItemMaintenance).single_click_pm? && params[:checklist_item_ids] && params[:checklist_item_ids].count > 1
      render json: {message: 'You are not authroized to do single click PM'}, status: 401 and return
    end
    if params[:record_id]
      @record = @maintainable.maintenance_records.find params[:record_id]
    else
      @record = @maintainable.maintenance_records.for_cycle(params[:cycle_id])
    end
    checklist_item_ids = (params[:checklist_item_ids] || []).map(&:to_i) - @record.checklist_item_maintenances.pluck(:maintenance_checklist_item_id)
    item_maintenance_ids = []
    checklist_item_ids.each do |item_id|
      checklist_item_maintenance = @record.checklist_item_maintenances.find_or_initialize_by(maintenance_checklist_item_id: item_id)

      if params[:status] == Maintenance::ChecklistItemMaintenance::STATUS_ISSUES.to_s
        checklist_item_maintenance.update_attributes status: params[:status]

        work_order = Maintenance::WorkOrder.new(work_order_params)
        work_order.checklist_item_maintenance = checklist_item_maintenance
        work_order.opened_by = current_user
        work_order.maintainable = @maintainable
        work_order.opened_at = Time.current
        work_order.status = Maintenance::WorkOrder::STATUS_OPEN
        work_order.assigned_to_id = current_user.wo_assignable_id
        work_order.priority = 'l'
        work_order.save
      else
        checklist_item_maintenance.update_attributes(status: params[:status], comment: params[:comment])
      end
      item_maintenance_ids << checklist_item_maintenance.id
    end

    @checklist_item_maintenances = @record.checklist_item_maintenances.where(id: item_maintenance_ids)
    render json: @checklist_item_maintenances.to_json(include: :work_order), status: 200
  end

  def inspect
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @inspection_detail = @checklist_item_maintenance.build_inspection_detail
    @work_order = @inspection_detail.build_work_order
    @work_order.maintainable = @maintainable
    @work_order.description = params[:comment]
    @work_order.opened_by = current_user
    @work_order.opened_at = Time.current
    @work_order.status = Maintenance::WorkOrder::STATUS_OPEN
    @work_order.priority = 'l'
    @work_order.checklist_item_maintenance = @checklist_item_maintenance
    completed_by = @checklist_item_maintenance.maintenance_record.completed_by
    @work_order.assigned_to_id = (completed_by && completed_by.wo_assignable_id) || Maintenance::WorkOrder::UNASSIGNED

    @inspection_detail.save

    render json: @inspection_detail.to_json(include: :work_order), status: 200
  end

  def cancel_inspect
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @inspection_work_order = @checklist_item_maintenance.inspection_work_order
    @inspection_work_order.destroy

    render json: @checklist_item_maintenance.id, status: 200
  end

  def destroy
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @checklist_item_maintenance.destroy
    render json: params[:id], status: 200
  end

  private

  def get_maintainable
    @maintainable = params[:maintainable_type].classify.constantize.find(params[:maintainable_id])
  end

  def work_order_params
    params.require(:maintenance_work_order).permit(
      :status, :description, :priority, :assigned_to_id, :maintainable_id, :maintainable_type, :other_maintainable_location, :due_to_date,
      attachments_attributes: [:id, :file, :_destroy ]
    )
  end

end

app/controllers/maintenance/checklist_items_controller.rb
class Maintenance::ChecklistItemsController < Maintenance::BaseController
  before_action :set_maintenance_checklist_item,only: [:update,:destroy]
  skip_before_action :check_current_cycles_are_finished

  def index
    @checklist_items = Maintenance::ChecklistItem.areas_with_subcategories
    render json: @checklist_items.to_json
  end

  def create
    @checklist_item = Maintenance::ChecklistItem.new checklist_item_params
    @checklist_item.user_id = current_user.id
    @checklist_item.save
    render json: @checklist_item.to_json(only: [:id, :name, checklist_items: []]), status: 200
  end

  def update
    @checklist_item.update checklist_item_params
    render nothing: true, status: 200
  end
  
  def destroy
    @checklist_item.update_attribute(:is_deleted, true)
    render nothing: true, status: 200
  end

  private
  
  def set_maintenance_checklist_item
    @checklist_item = Maintenance::ChecklistItem.find params[:id]
  end

  def checklist_item_params
    params.require(:checklist_item).permit(
        :name,
        :area_id,
        :maintenance_type,
        :public_area_id,
        :area_row_order_position,
        :item_row_order_position,
        :public_area_row_order_position
    )
  end
end

app/helpers/maintenance_helper.rb
module MaintenanceHelper

  def work_order_status_label_class(days_opened)
    if days_opened <= 2
      "label label-success"
    elsif days_opened <= 7
      "label label-warning"
    else
      "label label-danger"
    end
  end
  
  def work_order_priority_label_class(priority)
    if priority == "l"
      "text-success"
    elsif priority == "m"
      "text-warning"
    else
      "text-danger"
    end
  end

  def minutes_to_hours(minutes)
    return if minutes.nil?
    minutes % 30 == 0 ? "#{minutes / 60.0} hours" : "#{minutes} minutes"
  end

  def current_cycle_range
    current_cycle = Maintenance::Cycle.current
    start_date = Time.new(current_cycle.year, current_cycle.start_month)
    end_date = (start_date + (current_cycle.frequency_months - 1).months).end_of_month
    "#{start_date.strftime('%b %d')} - #{end_date.strftime('%b %d')}"
  end
  
  def users_in_current_property
    Property.current.users.active.select { |u| u.wo_assignable_id > 0 }.map{ |u| [u.name.titleize, u.id] } + Maintenance::WorkOrder::EXTRA_USERS
  end

  def default_assigned_to_user(work_order)
    if Property.current.users.include?(work_order.assigned_to)
      work_order.assigned_to_id
    else
      work_order.assigned_to_id || Maintenance::WorkOrder::UNASSIGNED
    end
  end

  def work_order_form_data_attributes(wo)
    {
      'permitted-priority' => policy(wo).permitted_attributes.include?(:priority),
      'permitted-status' => policy(wo).permitted_attributes.include?(:status),
      'permitted-assigned-to-id' => policy(wo).permitted_attributes.include?(:assigned_to_id),
      'permitted-due-to-date' => policy(wo).permitted_attributes.include?(:due_to_date),
      'user-permitted-to-edit-closed-wo' => policy(wo).edit_closed?,
      'wo-closed' => wo.closed?
    }
  end

  def properties_filter_class
    current_user.corporate? && current_user.all_properties.count > 0 ? '' : 'hidden'
  end

  def new_work_order_form_title
    @prev_property_id.nil? ? "Add WO for '#{Property.current.name}'" : 'Add Work Order'
  end

  def new_work_order_description_placeholder
    @prev_property_id.nil? ? "Describe the WO for '#{Property.current.name}'" : t('.description_placeholder')
  end

  def work_order_types
    [
      ['All WOs', nil],
      ['Filter WOs for: Room', 'Maintenance::Room'],
      ['Filter WOs for: Public Area', 'Maintenance::PublicArea'],
      ['Filter WOs for: Equipment', 'Maintenance::Equipment'],
      ['Filter WOs for: Other', 'Other']
    ]
  end

  def work_order_status_labels
    {
      Maintenance::WorkOrder::STATUS_OPEN => 'Open',
      Maintenance::WorkOrder::STATUS_WORKING => 'In Progress',
      Maintenance::WorkOrder::STATUS_CLOSED => 'Closed'
    }
  end

  def work_order_assigned_to(work_order)
    if work_order.assigned_to_id == Maintenance::WorkOrder::THIRD_PARTY
      t('reports.work_order_trendings.third_party')
    elsif work_order.assigned_to_id == Maintenance::WorkOrder::UNASSIGNED
      t('reports.work_order_trendings.unassigned')
    elsif work_order.assigned_to
      work_order.assigned_to.name
    else
      ""
    end
  end
end

app/views/maintenance/setup/index.html.slim
.row
  .col-md-6
    .panel.panel-default
      .panel-body
        h3= link_to 'Guest Rooms', maintenance_setup_rooms_path
  .col-md-6
    .panel.panel-default
      .panel-body
        h3= link_to 'Public Areas',maintenance_setup_public_areas_path
.row
  .col-md-6
    .panel.panel-default
      .panel-body
        h3= link_to 'Equipment', maintenance_setup_equipment_path

app/views/maintenance/setup/public_areas.html.slim
.page-header.page-header-block
  .page-header-section
    h4.title.semibold= t('.header')
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        h4
          p SET FREQUENCY
          p.ml15
            | Start month
            = select_tag :start_month, options_for_select((1..(@current_cycle ? 12 : Date.today.month)).collect { |month| [Date::MONTHNAMES[month], month] }, selected: @current_cycle.try(:pm_start_month)),
                         prompt: 'Select', class: 'form-control start-month-select', id: 'start-month', disabled: @current_cycle
          p.ml15
            | ONCE every
            = select_tag :public_area_frequency,
                         options_for_select(Maintenance::Cycle::FREQUENCIES, @current_cycle.try(:frequency_months)),
                         prompt: 'Select',
                         class: 'form-control frequency-select',
                         disabled: true
            | months
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        h4 Setup the maintenance public areas
        #public_areas
          .panel-group.public-areas-listing
          a.btn.btn-block.btn-default.add-area data-loading-text="saving public area..."
            span.ico-plus-sign
            = " Add Public Area"


script#public-area-template type="x-tmpl-mustache"
  .panel data-id="{{id}}" data-type="public-area"
    .panel-heading.btn-default
      h4.panel-title
        i.area-sort-handle.ico-sort.mr5
        a.text-primary.collapsed data-toggle="collapse" href="#collapse-{{id}}"
          span.plus.mr5
        a.x-editable.area-item data-title=("Edit public area") data-type="text" data-url="/maintenance/public_areas/{{id}}" data-send="always"
          | {{name}}
        a.area-deleteable.pull-right data-title=("Delete public area") data-type="text" data-area-id="{{id}}" data-heading="Confirm Public Area Deletion." data-message="Do you want to delete the public area? All checklist items under the public area will be deleted"
          i.ico-trash.text-danger.cursor-pointer
          
    div.panel-collapse.collapse id="collapse-{{id}}"
      .panel-body.checklist-items
        .panel-group.items-listing
          | {{#subcategories}}
          | {{>subcategory}}
          | {{/subcategories}}
        a.btn.btn-block.btn-default.add-item data-area-id="{{id}}" data-loading-text="saving item..."
          span.ico-plus-sign
          = " Add item"

script#checklist-subcategory-template type="x-tmpl-mustache"
  .panel data-id="{{id}}" data-type="item"
    .panel-heading
      h5
        i.area-sort-handle.ico-sort.mr5
        a.x-editable.checklist-item data-title=("Edit checklist item") data-type="text" data-url="/maintenance/checklist_items/{{id}}" data-send="always"
          | {{name}}
        a.x-deleteable.pull-right data-send="always" data-title=("Delete checklist item") data-type="text" data-checklist-id="{{id}}" data-heading="Confirm Public Area Maintenanance Checklist Item Deletion" data-message="Do you want to delete the checklist item?"
          i.ico-trash.text-danger.cursor-pointer
          


- content_for :js do
  coffee:
    delete_link = ''
    delete_area_link = ''
    public_areas = $('#public_areas')
    public_area_tmpl = $('#public-area-template').html() 
    checklist_subitem_tmpl = $('#checklist-subcategory-template').html()
    xeditable_area_options =
      params: (params)->
        {public_area: {name: params.value}}
      validate: (val)->
        return 'This field is required' if $.trim(val) is ''
    
    xeditable_options =
      params: (params)->
        {checklist_item: {name: params.value}}
      validate: (val)->
        return 'This field is required' if $.trim(val) is ''

    $.ajax(Routes.maintenance_public_areas_path(), { dataType: 'json' }).done (areas)->
      $(areas).each ->
        rendered_area = $(Mustache.render(public_area_tmpl, @, {subcategory: checklist_subitem_tmpl}))
        rendered_area.appendTo(public_areas.find('> .panel-group'))
      
      #ranking public areas
      public_areas.find('.public-areas-listing').sortable
        axis: "y"
        handle: '.area-sort-handle'
        cursor: "ns-resize"
        update: (event, ui) ->
          item_id = ui.item.data('id')
          item_type = ui.item.data('type')
          public_area_data = {}
          public_area_data["row_order_position"] = ui.item.index()
          $.ajax
            type: 'PATCH'
            url: Routes.maintenance_public_area_path(item_id)
            dataType: 'json'
            data: {public_area: public_area_data}
    
      #ranking checklist items
      public_areas.find('.items-listing').sortable
        axis: "y"
        handle: '.area-sort-handle'
        cursor: "ns-resize"
        update: (event, ui) ->
          item_id = ui.item.data('id')
          item_type = ui.item.data('type')
          checklist_item_data = {}
          checklist_item_data["public_area_row_order_position"] = ui.item.index()
          $.ajax
            type: 'PATCH'
            url: Routes.maintenance_checklist_item_path(item_id)
            dataType: 'json'
            data: {checklist_item: checklist_item_data}  

      public_areas.find('a.x-editable.area-item').editable(xeditable_area_options)
      public_areas.find('a.x-editable.checklist-item').editable(xeditable_options)
       
    
    # add a new public area item:
    public_areas.on 'click', '.add-area', ->
      link = $(@)
      link_html = link.html()
      link.html(link.data('loading-text')).attr('disabled', true)
      new_area_params = {name: 'New public area'}

      $.ajax Routes.maintenance_public_areas_path(),
        type: 'POST', data: {public_area: new_area_params}
      .done (data) ->
        template = public_area_tmpl
        
        link.siblings('.panel-group').append(Mustache.render(template, data)).find('a.x-editable.area-item').editable(xeditable_area_options)
      .always -> link.html(link_html).attr('disabled', false)
    
    # add new checklist item
    public_areas.on 'click', '.add-item', ->
      link = $(@)
      link_html = link.html()
      link.html(link.data('loading-text')).attr('disabled', true)
      new_item_params =
        name: 'New Item'
        maintenance_type: 'public areas'
        public_area_id: link.data('area-id')
        public_area_row_order_position: link.parent().find('.ui-sortable .panel').length

      $.ajax Routes.maintenance_checklist_items_path(),
        type: 'POST', data: {checklist_item: new_item_params}
      .done (data)->
        template = checklist_subitem_tmpl
        link.siblings('.panel-group').append(Mustache.render(template, data))
        link.siblings('.panel-group').find(':last-child a.x-editable').editable(xeditable_options)
      .always -> link.html(link_html).attr('disabled', false)    
     
    # delete public area:
    public_areas.on 'click', '.area-deleteable', ->
      delete_area_link = $(@)
      
      $('#ChecklistconfirmationDialog .checklist_heading').html(delete_area_link.data('heading'))
      $('#ChecklistconfirmationDialog .checklist_message').html(delete_area_link.data('message'))
      $('#ChecklistconfirmationDialog').modal('show')

    $('#ChecklistconfirmationDialog .confirm').on 'click', ->
      $.ajax Routes.maintenance_public_area_path({id: delete_area_link.data('area-id')}),
        type: 'DELETE',
      .done (data)->  
        delete_area_link.parent().parent().parent().remove();

    $('#ChecklistconfirmationDialog .modal-close').on 'click', ->
      $('#ChecklistconfirmationDialog').modal('hide')


    # delete checklist item:
    public_areas.on 'click', '.x-deleteable', ->
      delete_link = $(@)

      $('#ChecklistconfirmationDialog2 .checklist_heading').html(delete_link.data('heading'))
      $('#ChecklistconfirmationDialog2 .checklist_message').html(delete_link.data('message'))
      $('#ChecklistconfirmationDialog2').modal('show')

    $('#ChecklistconfirmationDialog2 .confirm').on 'click', ->
      $.ajax Routes.maintenance_checklist_item_path({id: delete_link.data('checklist-id')}),
        type: 'DELETE',
      .done (data)->  
        delete_link.parent().parent().parent().remove()

    $('#ChecklistconfirmationDialog2 .modal-close').on 'click', ->
      $('#ChecklistconfirmationDialog2').modal('hide')
    
    
    #
    #  Cycles:
    #
    $start_month = $('#start-month')
    $frequency = $('#public_area_frequency')
    create_cycle = () ->
      start_month = $start_month.val()
      frequency = $frequency.val()
      return unless !!start_month && !!frequency
      $.ajax(
        url: Routes.maintenance_cycles_path()
        type: 'POST'
        dataType: 'json'
        data:
          start_month: start_month || 1
          frequency: frequency
          cycle_type: 'public_area'
      ).done((data) ->
        $.gritter.add
          time: 5000
          text: data.message
          class_name: "alert alert-success"
        $frequency.val(data.cycle.frequency_months)
        $start_month.attr('disabled', 'disabled')
        $frequency.attr('disabled', 'disabled')
      ).fail((xhr) ->
        response = $.parseJSON(xhr.responseText).error
        $.gritter.add
          time: 5000
          text: response
          class_name: "alert alert-danger"
      )

    $start_month.on 'change', (e) ->
      unless $start_month.val()
        $frequency.attr('disabled', 'disabled')
      else
        $frequency.removeAttr('disabled')

    $frequency.on 'change', (e) ->
      create_cycle()

#ChecklistconfirmationDialog.modal aria-hidden="true" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        a.close data-dismiss="modal"  ×
        h4.checklist_heading 
      .modal-body
        p.checklist_message
      .modal-footer
        button.btn.modal-close aria-hidden="true"  NO! this was a terrible idea.
        a.btn.btn-danger.confirm data-dismiss="modal"  YES I'm sure! 

#ChecklistconfirmationDialog2.modal aria-hidden="true" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        a.close data-dismiss="modal"  ×
        h4.checklist_heading 
      .modal-body
        p.checklist_message
      .modal-footer
        button.btn.modal-close aria-hidden="true"  NO! this was a terrible idea.
        a.btn.btn-danger.confirm data-dismiss="modal"  YES I'm sure!
    


    